### ISSUE TITLE
How to update CumulsMX

### ISSUE THREAD

**Issue by Triglia118** [optoisolated/MXWeather#11]
Hi, is there a way to update CumulsMX container to the latest version of the program, without building everything from scratch?
Would be great to avoid to configure everything again....
Thank you

**Comment by optoisolated** [comment]
If the container is deployed per the instructions, it should retain all settings when you re-run the build command. 

I have a cron job that runs nightly to rebuild the environment; this ensures i'm always running the latest build. The container is configured to store all data generated external to the container, so rebuilding or even deleting and recreating the container will have no impact on the data. As long as the config,data and reports  directories remain untouched in the docker container source folder.

**Comment by Triglia118** [comment]
You are right. In my case (OpenWRT as docker host), it is enough to type the following:

`docker stop MXWeather && docker rm MXWeather
docker build -t ubuntu:MXWeather . --build-arg CACHEBUST=$(date +%s)`

then just start the docker with my own settings from the GUI. All OK, thank you
